version: '3'

services:
    base:
        build: .
        volumes:
          - .:/app
        env_file:
          - .env
        command: 'false'

    app:
        extends:
            service: base
        depends_on:
            - migrations
        command: flask run --host=0.0.0.0
        ports:
            - "5000:5000"

    migrations:
        extends:
            service: base
        command: flask db upgrade
